#ifndef UTILITYPROXIES_GLOBAL_H
#define UTILITYPROXIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UTILITYPROXIES_LIBRARY)
#  define UTILITYPROXIESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UTILITYPROXIESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UTILITYPROXIES_GLOBAL_H
